# Generated by Django 2.0.1 on 2018-01-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restexample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='owner',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='restexample.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='description',
            field=models.TextField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='restexample.Category'),
        ),
    ]
