# Generated by Django 2.0.1 on 2018-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restexample', '0004_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
